pipeline {
  agent none
  stages {
    stage('Fluffy Build') {
      parallel {
        stage('Build Java 7') {
          agent {
            node {
              label 'java7'
            }

          }
          steps {
            sh './jenkins/build.sh'
            archiveArtifacts(artifacts: 'target/*.jar', fingerprint: true)
            stash(name: 'Java 7', includes: 'target/**')
          }
        }

        stage('Build Java 8') {
          agent {
            node {
              label 'java8'
            }

          }
          steps {
            sh './jenkins/build.sh'
            stash(name: 'Java 8', includes: 'target/**')
          }
        }

      }
    }

    stage('Fluffy Test') {
      parallel {
        stage('Backend Java 7') {
          agent {
            node {
              label 'java7'
            }

          }
          steps {
            unstash 'Java 7'
            sh './jenkins/test-backend.sh'
            archiveArtifacts 'target/surefire-reports/**/TEST*.xml'
          }
        }

        stage('Backend Java 8') {
          agent {
            node {
              label 'java8'
            }

          }
          steps {
            unstash 'Java 8'
            sh './jenkins/test-backend.sh'
            archiveArtifacts 'target/surefire-reports/**/TEST*.xml'
          }
        }

      }
    }

    stage('Confirm Deploy to staging') {
      when {
        branch 'when-directive-test'
      }
      steps {
        input(message: 'Okay to deploy to staging?', ok: 'Yes')
      }
    }

    stage('Deploy to Staging') {
      agent {
        node {
          label 'java8'
        }

      }
      when {
        branch 'when-directive-test'
      }
      steps {
        unstash 'Java 7'
        sh './jenkins/deploy.sh staging'
      }
    }

  }
}