pipeline {
  agent none
  stages {
    stage('Fluffy Build') {
      parallel {
        stage('Build Java 7') {
          agent {
            node {
              label 'java7'
            }

          }
          steps {
            sh './jenkins/build.sh'
            archiveArtifacts(artifacts: 'target/*.jar', fingerprint: true)
          }
        }

        stage('Build Java 8') {
          agent {
            node {
              label 'java8'
            }

          }
          environment {
            BUZZ_NAME = 'Java 8 Bee'
          }
          steps {
            sh './jenkins/build.sh'
            archiveArtifacts(artifacts: 'target/*.jar', fingerprint: true)
          }
        }

      }
    }

    stage('Fluffy Test') {
      parallel {
        stage('Backend') {
          agent {
            node {
              label 'java7'
            }

          }
          steps {
            sh './jenkins/test-backend.sh'
            archiveArtifacts 'target/surefire-reports/**/TEST*.xml'
          }
        }

        stage('Frontend') {
          agent {
            node {
              label 'java7'
            }

          }
          steps {
            sh './jenkins/test-frontend.sh'
            junit 'target/test-results/**/TEST*.xml'
          }
        }

        stage('Performance') {
          agent {
            node {
              label 'java7'
            }

          }
          steps {
            sh './jenkins/test-performance.sh'
          }
        }

        stage('Static') {
          agent {
            node {
              label 'java7'
            }

          }
          steps {
            sh './jenkins/test-static.sh'
          }
        }

      }
    }

    stage('Fluffy Deploy') {
      agent {
        node {
          label 'java7'
        }

      }
      steps {
        sh './jenkins/deploy.sh staging'
      }
    }

  }
}