pipeline {
  agent none
  stages {
    stage('Fluffy Build') {
      parallel {
        stage('Build Java 7') {
          agent {
            node {
              label 'java7'
            }

          }
          steps {
            sh './jenkins/build.sh'
            archiveArtifacts(artifacts: 'target/*.jar', fingerprint: true)
            stash(name: 'Buzz Java 7', includes: 'target/**')
          }
        }

        stage('Build Java 8') {
          agent {
            node {
              label 'java8'
            }

          }
          environment {
            BUZZ_NAME = 'Java 8 Bee'
          }
          steps {
            sh './jenkins/build.sh'
            archiveArtifacts(artifacts: 'target/*.jar', fingerprint: true)
            stash(name: 'Buzz Java 8', includes: 'target/**')
          }
        }

      }
    }

    stage('Fluffy Test') {
      parallel {
        stage('Backend jdk7') {
          agent {
            node {
              label 'java7'
            }

          }
          steps {
            unstash 'Buzz Java 7'
            sh './jenkins/test-backend.sh'
            archiveArtifacts 'target/surefire-reports/**/TEST*.xml'
          }
        }

        stage('Frontend jdk7') {
          agent {
            node {
              label 'java7'
            }

          }
          steps {
            unstash 'Buzz Java 7'
            sh './jenkins/test-frontend.sh'
            junit 'target/test-results/**/TEST*.xml'
          }
        }

        stage('Performance') {
          agent {
            node {
              label 'java7'
            }

          }
          steps {
            sh './jenkins/test-performance.sh'
          }
        }

        stage('Static') {
          agent {
            node {
              label 'java7'
            }

          }
          steps {
            sh './jenkins/test-static.sh'
          }
        }

        stage('Testing A jdk8') {
          agent {
            node {
              label 'java8'
            }

          }
          steps {
            unstash 'Buzz Java 8'
            sh './jenkins/test-backend.sh'
          }
        }

        stage('Testing B jdk8') {
          agent {
            node {
              label 'java8'
            }

          }
          steps {
            unstash 'Buzz Java 8'
            sh './jenkins/test-backend.sh'
          }
        }

      }
    }

    stage('Confirm to Deploy ') {
      steps {
        input(message: 'Deploy to staging?', ok: 'Yes, let\'s do it')
      }
    }

    stage('Deploy to Staging') {
      agent {
        node {
          label 'java8'
        }

      }
      steps {
        unstash 'Buzz Java 8'
        sh './jenkins/deploy.sh staging'
      }
    }

  }
}